version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - troyrc_ota_DB__uri=postgresql://postgres:postgres@db:5432/troyrc_ota
      - troyrc_ota_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: troyrc_ota_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/troyrc_ota_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=troyrc_ota, troyrc_ota_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
